SELECT cu.[No_] AS [customer_id]
	,NULLIF(cu.[Name], '') AS [customer_name]
	,NULLIF(cu.[Address], '') AS [address]
	,NULLIF(cu.[Address 2], '') AS [address_2]
	,NULLIF(cu.[City], '') AS [city]
	,NULLIF(cu.[County], '') AS [county]
	,NULLIF(cu.[Country_Region Code], '') AS [country_id]
	,NULLIF(cu.[Post Code], '') AS [post_code]
	,NULLIF(cu.[Territory Code], '') AS [territory_code]
	,NULLIF(cu.[Contact], '') AS [contact_name]
	,NULLIF(cu.[Phone No_], '') AS [phone_no]
	,NULLIF(cu.[Mobile Phone No_], '') AS [mobile_phone_no]
	,NULLIF(cu.[E-Mail], '') AS [email]
	,NULLIF(cu.[Home Page], '') AS [home_page]
	,NULLIF(cu.[Primary Contact No_], '') AS [primary_contact_no]
	,NULLIF(cu.[Our Account No_], '') AS [our_account_no]
	,COALESCE(NULLIF(cu.[Currency Code], ''), 'USD') AS [currency_code]
	,cu.[Credit Limit (LCY)] AS [credit_limit_lcy]
	,NULLIF(cu.[Customer Posting Group], '') AS [customer_posting_group]
	,NULLIF(cu.[Gen_ Bus_ Posting Group], '') AS [general_business_posting_group]
	,NULLIF(cu.[VAT Bus_ Posting Group], '') AS [vat_business_posting_group]
	,NULLIF(cu.[Customer Price Group], '') AS [customer_price_group]
	,NULLIF(cu.[Customer Disc_ Group], '') AS [customer_discount_group]
	,NULLIF(cu.[Payment Terms Code], '') AS [payment_terms_code]
	,NULLIF(cu.[Payment Method Code], '') AS [payment_method_code]
	,NULLIF(cu.[Shipment Method Code], '') AS [shipment_method_code]
	,NULLIF(cu.[Shipping Agent Code], '') AS [shipping_agent_code]
	,NULLIF(cu.[Location Code], '') AS [location_code]
	,CAST(NULL AS NVARCHAR(10)) AS [type_of_supply_code]
	,CAST(NULL AS NVARCHAR(30)) AS [type_of_supply_description]
	,NULLIF(cu.[Salesperson Code], '') AS [salesperson_id]
	,cu.[Blocked] AS [blocked]
	,NULLIF(cu.[Bill-to Customer No_], '') AS [bill_to_customer_id]
	,cu.[Prices Including VAT] AS [prices_including_vat]
	,NULLIF(cu.[VAT Registration No_], '') AS [vat_reg_no]
	,CAST(NULL AS NVARCHAR(50)) AS [registration_no]
	,NULLIF(cu.[EORI Number], '') AS [eori_no]
	,cu.[Last Modified Date Time] AS [last_modified]

FROM [Example USA Master Setup$Customer$437dbf0e-84ff-417a-965d-ed2bb9650972] AS cu;
