SELECT it.[No_]                                                             AS [item_id]
    ,it.[Vendor Item No_]                                                   AS [vendor_reference]
    ,LEFT(it.[No_], 3)                                                      AS [brand_id]
    ,it.[Description]                                                       AS [description]
    ,it.[Description 2]                                                     AS [description_2]
    ,''                                                                     AS [colours]
    ,''                                                                     AS [size_1]
    ,''                                                                     AS [size_1_unit]
    ,''                                                                     AS [eu_size]
    ,''                                                                     AS [eu_size_unit]
    ,''                                                                     AS [us_size]
    ,''                                                                     AS [us_size_unit]
    ,''                                                                     AS [season]
    ,'LLC Item Only'                                                        AS [item_info]
    ,REPLACE(LEFT(it.[Item Category Code], CHARINDEX(CHAR(95),
        it.[Item Category Code])), CHAR(95), '')                            AS [category_code]
    ,SUBSTRING(it.[Item Category Code], CHARINDEX(CHAR(95),
        it.[Item Category Code]) + 1, LEN(it.[Item Category Code]) 
        - CHARINDEX(CHAR(95), it.[Item Category Code]))                     AS [group_code]
     ,it.[GTIN]                                                             AS [ean_barcode]
    ,''                                                                     AS [tariff_no]
    ,it.[Tariff No_]                                                        AS [hts_no]
    ,0                                                                      AS [gbp_cost]
    ,0                                                                      AS [gbp_trade]
    ,0                                                                      AS [gbp_srp]
    ,0                                                                      AS [eur_cost]
    ,0                                                                      AS [eur_trade]
    ,0                                                                      AS [eur_srp]
    ,it.[Unit Cost]                                                         AS [usd_cost]
    ,it.[Unit Price]                                                        AS [usd_trade]
    ,rp.[RRP]                                                               AS [usd_srp]
    ,''                                                                     AS [uk_eu_vendor_no]
    ,it.[Vendor No_]                                                        AS [us_vendor_no]
    ,0                                                                      AS [ltd_blocked]
    ,0                                                                      AS [bv_blocked]
    ,it.[Blocked]                                                           AS [llc_blocked]
    ,0                                                                      AS [pref_sale]
    ,it.[Country_Region of Origin Code]                                     AS [coo]
    ,it.[Base Unit of Measure]                                              AS [unit_of_measure]
    ,0                                                                      AS [hot_product]
    ,30                                                                     AS [lead_time_days]
    ,0                                                                      AS [bread_butter]
    ,0                                                                      AS [ltd_buffer_stock]
    ,0                                                                      AS [bv_buffer_stock]
    ,CAST(NULL AS NVARCHAR(30))                                              AS [common_item_no]
    ,''                                                                     AS [d2c_master_sku]
    ,0                                                                      AS [d2c_web_item]
    ,NULL                                                                   AS [record_id]

FROM [Example USA Master Setup$Item$437dbf0e-84ff-417a-965d-ed2bb9650972] AS it
LEFT JOIN [ERP_LIVE_US].[dbo].[Example USA Master Setup$Item$3e6912b5-53d7-4158-bed2-83325a3a82a9] AS rp
    ON it.[No_] = rp.[No_]
WHERE LEN(it.[No_]) <= 20;
