SELECT 'Example LLC' AS [entity]
	,pl.[Document Type] AS [document_type]
	,'Order' AS [document_type_name]
	,pl.[Document No_] AS [document_no]
	,pl.[Line No_] AS [line_no]
	,CASE WHEN pl.[Type] = 2 THEN NULLIF(pl.[No_], '') END AS [item_id]
	,NULLIF(pl.[Buy-from Vendor No_], '') AS [vendor_id]
	,NULLIF(pl.[Pay-to Vendor No_], '') AS [pay_to_vendor_id]
	,NULLIF(pl.[Location Code], '') AS [location_code]
	,NULLIF(pl.[Unit of Measure Code], '') AS [unit_of_measure_code]
	,NULLIF(ph.[Purchaser Code], '') AS [purchaser_code]
	,COALESCE(NULLIF(ph.[Currency Code], ''), 'USD') AS [currency_code]
	,ph.[Currency Factor] AS [currency_factor]
	,ph.[Status] AS [document_status]
	,CASE ph.[Status]
		WHEN 0 THEN 'Open'
		WHEN 1 THEN 'Released'
		WHEN 2 THEN 'Pending Approval'
		WHEN 3 THEN 'Pending Prepayment'
		ELSE 'Unknown'
	END AS [document_status_name]
	,NULLIF(CAST(ph.[Order Date] AS DATE), '17530101') AS [order_date]
	,NULLIF(CAST(ph.[Document Date] AS DATE), '17530101') AS [document_date]
	,NULLIF(CAST(ph.[Posting Date] AS DATE), '17530101') AS [posting_date]
	,NULLIF(CAST(pl.[Expected Receipt Date] AS DATE), '17530101') AS [expected_receipt_date]
	,NULLIF(CAST(pl.[Requested Receipt Date] AS DATE), '17530101') AS [requested_receipt_date]
	,NULLIF(CAST(pl.[Promised Receipt Date] AS DATE), '17530101') AS [promised_receipt_date]
	,NULLIF(CAST(pl.[Planned Receipt Date] AS DATE), '17530101') AS [planned_receipt_date]
	,NULLIF(CAST(ph.[Due Date] AS DATE), '17530101') AS [due_date]
	,NULLIF(ph.[Your Reference], '') AS [your_reference]
	,NULLIF(ph.[Vendor Order No_], '') AS [vendor_order_no]
	,NULLIF(ph.[Vendor Invoice No_], '') AS [vendor_invoice_no]
	,NULLIF(ph.[Shipment Method Code], '') AS [shipment_method_code]
	,NULLIF(pl.[Shortcut Dimension 1 Code], '') AS [country_dimension_code]
	,NULLIF(pl.[Shortcut Dimension 2 Code], '') AS [brand_dimension_code]
	,CAST(pl.[Drop Shipment] AS BIT) AS [drop_shipment]
	,pl.[Quantity] AS [quantity]
	,pl.[Quantity Received] AS [quantity_received]
	,pl.[Quantity Invoiced] AS [quantity_invoiced]
	,pl.[Qty_ to Receive] AS [quantity_to_receive]
	,pl.[Outstanding Quantity] AS [outstanding_quantity]
	,pl.[Direct Unit Cost] AS [direct_unit_cost]
	,pl.[Unit Cost (LCY)] AS [unit_cost_lcy]
	,pl.[Line Discount _] AS [line_discount_percent]
	,pl.[Line Discount Amount] AS [line_discount_amount]
	,pl.[Line Amount] AS [line_amount]
	,pl.[Amount Including VAT] AS [amount_including_vat]
	,pl.[Outstanding Amount] AS [outstanding_amount]
	,pl.[Outstanding Amount (LCY)] AS [outstanding_amount_lcy]
	,CAST(NULL AS BIT) AS [afloat]
	,CAST(NULL AS NVARCHAR(50)) AS [container_no]
	,CAST(NULL AS NVARCHAR(50)) AS [waybill_no]
	,CAST(NULL AS DATE) AS [date_afloat]
	,CAST(NULL AS DATE) AS [requested_xf_date]
	,CAST(NULL AS DATE) AS [promised_xf_date]
	,CAST(NULL AS DATE) AS [actual_xf_date]
	,CAST(NULL AS DATE) AS [deposit_payment_date]
	,CAST(NULL AS DATE) AS [balance_payment_date]
	,CAST(NULL AS NVARCHAR(80)) AS [external_reference]
	,CAST(NULL AS NVARCHAR(20)) AS [intercompany_document_no]
	,CAST(NULL AS BIT) AS [sent_to_3pl]
	,CAST(NULL AS DATETIME) AS [sent_to_3pl_at]
	,NULLIF(ph.[$systemModifiedAt], '17530101') AS [last_modified]

FROM [Example USA Master Setup$Purchase Line$437dbf0e-84ff-417a-965d-ed2bb9650972] AS pl

INNER JOIN [Example USA Master Setup$Purchase Header$437dbf0e-84ff-417a-965d-ed2bb9650972] AS ph
	ON ph.[Document Type] = pl.[Document Type]
	AND ph.[No_] = pl.[Document No_]

WHERE pl.[Document Type] = 1;
