SELECT ve.[No_] AS [vendor_id]
	,NULLIF(ve.[Name], '') AS [vendor_name]
	,NULLIF(ve.[Address], '') AS [address]
	,NULLIF(ve.[Address 2], '') AS [address_2]
	,NULLIF(ve.[City], '') AS [city]
	,NULLIF(ve.[County], '') AS [county]
	,NULLIF(ve.[Post Code], '') AS [post_code]
	,NULLIF(ve.[Country_Region Code], '') AS [country_id]
	,NULLIF(ve.[Contact], '') AS [contact_name]
	,NULLIF(ve.[Phone No_], '') AS [phone_no]
	,NULLIF(ve.[Mobile Phone No_], '') AS [mobile_phone_no]
	,NULLIF(ve.[E-Mail], '') AS [email]
	,NULLIF(ve.[Home Page], '') AS [home_page]
	,NULLIF(ve.[Primary Contact No_], '') AS [primary_contact_no]
	,NULLIF(ve.[Our Account No_], '') AS [our_account_no]
	,NULLIF(ve.[Global Dimension 1 Code], '') AS [country_dimension]
	,NULLIF(ve.[Vendor Posting Group], '') AS [vendor_posting_group]
	,NULLIF(ve.[Gen_ Bus_ Posting Group], '') AS [general_business_posting_group]
	,NULLIF(ve.[VAT Bus_ Posting Group], '') AS [vat_business_posting_group]
	,COALESCE(NULLIF(ve.[Currency Code], ''), 'USD') AS [currency_code]
	,NULLIF(ve.[Payment Terms Code], '') AS [payment_terms_code]
	,NULLIF(ve.[Payment Method Code], '') AS [payment_method_code]
	,NULLIF(ve.[Purchaser Code], '') AS [purchaser_code]
	,NULLIF(ve.[Shipment Method Code], '') AS [shipment_method_code]
	,NULLIF(ve.[Location Code], '') AS [location_code]
	,NULLIF(ve.[Lead Time Calculation], '') AS [lead_time_calculation]
	,ve.[Blocked] AS [blocked]
	,NULLIF(ve.[Pay-to Vendor No_], '') AS [pay_to_vendor_id]
	,NULLIF(ve.[VAT Registration No_], '') AS [vat_registration_no]
	,CAST(NULL AS NVARCHAR(50)) AS [registration_no]
	,NULLIF(ve.[EORI Number], '') AS [eori_no]
	,ve.[Last Modified Date Time] AS [last_modified]

FROM [Example USA Master Setup$Vendor$437dbf0e-84ff-417a-965d-ed2bb9650972] AS ve;
