USE [data_control];

GO

SET ANSI_NULLS ON;

GO

SET QUOTED_IDENTIFIER ON;

GO


CREATE OR ALTER VIEW [planning].[weekly_demand_actuals]
AS

/*
    Observed weekly external demand at the initial forecasting grain.

    This view contains active weeks only. Explicit zero-demand weeks will be
    generated by the modelling-calendar layer in Step 3.
*/

SELECT
     [week_start]
    ,[planning_entity]
    ,[brand_id]
    ,[category_code]
    ,[group_code]
    ,SUM([net_units]) AS [net_units]
    ,SUM([gross_units]) AS [gross_units]
    ,SUM([return_units]) AS [return_units]
    ,SUM([gbp_sales]) AS [gbp_sales]
    ,SUM([gbp_adjusted_margin]) AS [gbp_adjusted_margin]
    ,COUNT_BIG(*) AS [sales_line_count]
    ,COUNT(DISTINCT [customer_id]) AS [customer_count]
    ,COUNT(DISTINCT [item_id]) AS [item_count]
FROM [planning].[external_sales]
GROUP BY
     [week_start]
    ,[planning_entity]
    ,[brand_id]
    ,[category_code]
    ,[group_code];

GO
